### ISSUE TITLE
Add link to anonymyous form

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymcon#18]
See oriols comment linked below 

_Originally posted by @OriolAbril in https://github.com/pymc-devs/pymcon/pull/17/files_

**Comment by OriolAbril** [comment]
This was not meant to be a link to the annonymous form. This is an alternative way of reporting that bypasses the form. 

Imagine someone had a complain about Alex and me. Even if the report is anonymous, we are still the ones reviewing it, so we would have a confilct of interest. In case of a conflict of interest we would warn and remove ourselves from the decision process, but if the complain were about us, it is understandable that the reporter may worry about us ignoring the report instead of removing ourselves. This provides a way to contact you and Thomas so that we never even get the report (in the same way that one can raise a report to the numfocus board if the reporter suspects the code of conduct enforcing committee has a confilct of interest. 

You and @twiecki  have to be okay with it too though and we have to fix the link.

**Comment by canyon289** [comment]
Yes this is tricky because @twiecki and I could have a conflict of interest as well. Either way I'm confused because if we replace the form, then the other mechanism is also suspect to the same bias right?

**Comment by OriolAbril** [comment]
The idea isn't to replace the form, the way to go is the form or emal me or Alex.

This is because either if you email me or Alex or you fill the form anonymously, the ones who will review the report will be me and Alex. This can be far from ideal in some cases (as I was saying above, a complain about Alex and me) to the point that could prevent issuing a report. This is why I wanted to provide an alternative (like numfocus does) so that if necessary a report could be filled making sure that neither me nor alex will review it. The two alternatives that come to mind are reporting to numfocus or reporting to you guys as executive committee. We can do one of them or both, depending on how you see it

also tagging @AlexAndorra

**Comment by canyon289** [comment]
We should let NumFOCUS review because they're neutral and not a part of this conference. If it's Thomas or I then the same issue could occur
